name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'  # Trigger this action when a version tag is pushed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.9'

      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      - name: Publish to pub.dev
        run: echo 'y' | flutter pub publish --force
