name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'  # Trigger this action when a version tag is pushed

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.9'

      - name: Disable Flutter telemetry
        run: flutter --disable-telemetry

      - name: Publish to pub.dev
        env:
          PUB_ACCESS_TOKEN: ${{ secrets.PUB_ACCESS_TOKEN }}
        run: |
          echo 'PUB_ACCESS_TOKEN=$PUB_ACCESS_TOKEN' > $HOME/.pub-cache/credentials.json
          flutter pub publish --force
